name: exposeTests
on: 
    workflow_call:

jobs:
    ExposeTest:
        runs-on: ubuntu-latest
        steps:
            - name: Get green it report zip
              uses: actions/download-artifact@v3
              with:
                name: green-it-report
                path: /home/runner/work/output
            - name: Serve Files
              uses: pavi2410/html-preview-action@v2
              with:
                html_file: 'global.html'
            - name: create link to go to html file exposition
              uses: github-actions-up-and-running/pr-comment@v1.0.0 
              env:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                myInput: ${{ format('[Click here to preview HTML page in browser]({0})', steps.html_preview.outputs.url) }}
        
    