name: exposeTests
on: 
    workflow_call:

jobs:
    ExposeTest:
        runs-on: ubuntu-latest
        steps:
            - name: Get green it report zip
              uses: actions/download-artifact@v3
              with:
                name: green-it-report
                path: /home/runner/work/output
            - name: Serve Files
              id: html_preview
              uses: pavi2410/html-preview-action@v2
              with:
                html_file: 'home/runner/work/output/global.html'
            - name: create link to go to html file exposition
              run:
                echo ${{steps.html_preview.outputs.url}}
        
    